version: "3.8"
services:
  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  server:
    image: node:18
    working_dir: /app
    volumes:
      - ./server:/app
    command: sh -c "npm install && npm start"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/mern_todos
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  client:
    image: node:18
    working_dir: /app
    volumes:
      - ./client:/app
    command: sh -c "npm install && npm start"
    ports:
      - "3000:3000"
    depends_on:
      - server

volumes:
  mongo-data:
